spring.application.name=company-resource-api

server.port=9051

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/company_resource
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9009/realms/company-access-realm
